name:                type-safe-ws
version:             0.1.0.0
github:              "githubuser/type-safe-ws"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/type-safe-ws#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- transformers
- servant
- servant-server
- text
- time
- aeson
- configurator
- warp
- postgresql-simple
- postgresql-simple-migration
- mtl
- process
- resource-pool
- githash
- containers
- protolude

library:
  source-dirs: src/lib
  default-extensions:  OverloadedStrings
                     , RecordWildCards
                     , NoImplicitPrelude

executables:
  type-safe-ws-exe:
    main:                Main.hs
    source-dirs:         src/app
    default-extensions:  OverloadedStrings
                       , RecordWildCards
                       , NoImplicitPrelude
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-unused-binds
    - -fno-warn-unused-do-bind
    - -fno-warn-unused-imports
    - -fno-warn-type-defaults
    dependencies:
    - type-safe-ws

tests:
  type-safe-ws-test:
    main:                Spec.hs
    source-dirs:         test
    default-extensions:  OverloadedStrings
                       , RecordWildCards
                       , NoImplicitPrelude
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-unused-binds
    - -fno-warn-unused-do-bind
    - -fno-warn-unused-imports
    - -fno-warn-type-defaults
    dependencies:
    - hspec
    - hspec-wai
    - hspec-wai-json
    - http-types
    - type-safe-ws
